import type { LucideIcon } from 'lucide-react';
import {
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowDownToLine,
  ArrowLeft,
  ArrowUp,
  ArrowUpToLine,
  Bell,
  BookOpen,
  Bot,
  Box,
  Boxes,
  Bug,
  Building2,
  Calendar,
  CalendarClock,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleCheckBig,
  CircleDashed,
  CirclePause,
  CircleX,
  Clock,
  Clock3,
  Cloud,
  Code,
  Code2,
  Copy,
  Cpu,
  CreditCard,
  DollarSign,
  Download,
  EllipsisVertical,
  ExternalLink,
  Eye,
  Facebook,
  FileCode,
  FileText,
  FlaskConical,
  Folder,
  FolderGit,
  FolderOpen,
  FolderX,
  Gamepad2,
  GitBranch,
  GitFork,
  GitPullRequest,
  Github,
  Globe,
  Hammer,
  History,
  Info,
  Key,
  KeyRound,
  Layers,
  Layers3,
  LayoutGrid,
  Lightbulb,
  List,
  ListChecks,
  ListTodo,
  Loader2,
  LoaderCircle,
  LogOut,
  Mail,
  Megaphone,
  Menu,
  Merge,
  MessageCircle,
  MessageCircleQuestion,
  MessageSquare,
  MessagesSquare,
  Microchip,
  Minimize2,
  Minus,
  Monitor,
  MoreHorizontal,
  MoreVertical,
  Package,
  PanelRightClose,
  PanelRightOpen,
  Paperclip,
  Pause,
  PauseCircle,
  Pencil,
  Pin,
  PinOff,
  Play,
  PlayCircle,
  Plus,
  Power,
  PowerOff,
  Puzzle,
  RefreshCw,
  RotateCcw,
  Search,
  Send,
  Server,
  Settings,
  Settings2,
  Share2,
  Shield,
  ShieldCheck,
  Slack,
  Smartphone,
  Sparkles,
  Square,
  SquareKanban,
  StickyNote,
  StopCircle,
  Terminal,
  TestTube,
  ThumbsDown,
  ThumbsUp,
  Trash,
  Trash2,
  TriangleAlert,
  User,
  UserCircle2,
  Users,
  Webhook,
  Wrench,
  X,
  XCircle,
  Zap,
} from 'lucide-react';

/** Every Lucide icon name imported under `src/` (deduped, sorted). Keep in sync via repo script if needed. */
export const prototypeLucideIconEntries: { name: string; Icon: LucideIcon }[] = [
  { name: 'AlertCircle', Icon: AlertCircle },
  { name: 'AlertTriangle', Icon: AlertTriangle },
  { name: 'Archive', Icon: Archive },
  { name: 'ArrowDown', Icon: ArrowDown },
  { name: 'ArrowDownToLine', Icon: ArrowDownToLine },
  { name: 'ArrowLeft', Icon: ArrowLeft },
  { name: 'ArrowUp', Icon: ArrowUp },
  { name: 'ArrowUpToLine', Icon: ArrowUpToLine },
  { name: 'Bell', Icon: Bell },
  { name: 'BookOpen', Icon: BookOpen },
  { name: 'Bot', Icon: Bot },
  { name: 'Box', Icon: Box },
  { name: 'Boxes', Icon: Boxes },
  { name: 'Bug', Icon: Bug },
  { name: 'Building2', Icon: Building2 },
  { name: 'Calendar', Icon: Calendar },
  { name: 'CalendarClock', Icon: CalendarClock },
  { name: 'Check', Icon: Check },
  { name: 'CheckCircle', Icon: CheckCircle },
  { name: 'CheckCircle2', Icon: CheckCircle2 },
  { name: 'ChevronDown', Icon: ChevronDown },
  { name: 'ChevronLeft', Icon: ChevronLeft },
  { name: 'ChevronRight', Icon: ChevronRight },
  { name: 'ChevronUp', Icon: ChevronUp },
  { name: 'Circle', Icon: Circle },
  { name: 'CircleCheckBig', Icon: CircleCheckBig },
  { name: 'CircleDashed', Icon: CircleDashed },
  { name: 'CirclePause', Icon: CirclePause },
  { name: 'CircleX', Icon: CircleX },
  { name: 'Clock', Icon: Clock },
  { name: 'Clock3', Icon: Clock3 },
  { name: 'Cloud', Icon: Cloud },
  { name: 'Code', Icon: Code },
  { name: 'Code2', Icon: Code2 },
  { name: 'Copy', Icon: Copy },
  { name: 'Cpu', Icon: Cpu },
  { name: 'CreditCard', Icon: CreditCard },
  { name: 'DollarSign', Icon: DollarSign },
  { name: 'Download', Icon: Download },
  { name: 'EllipsisVertical', Icon: EllipsisVertical },
  { name: 'ExternalLink', Icon: ExternalLink },
  { name: 'Eye', Icon: Eye },
  { name: 'Facebook', Icon: Facebook },
  { name: 'FileCode', Icon: FileCode },
  { name: 'FileText', Icon: FileText },
  { name: 'FlaskConical', Icon: FlaskConical },
  { name: 'Folder', Icon: Folder },
  { name: 'FolderGit', Icon: FolderGit },
  { name: 'FolderOpen', Icon: FolderOpen },
  { name: 'FolderX', Icon: FolderX },
  { name: 'Gamepad2', Icon: Gamepad2 },
  { name: 'GitBranch', Icon: GitBranch },
  { name: 'GitFork', Icon: GitFork },
  { name: 'GitPullRequest', Icon: GitPullRequest },
  { name: 'Github', Icon: Github },
  { name: 'Globe', Icon: Globe },
  { name: 'Hammer', Icon: Hammer },
  { name: 'History', Icon: History },
  { name: 'Info', Icon: Info },
  { name: 'Key', Icon: Key },
  { name: 'KeyRound', Icon: KeyRound },
  { name: 'Layers', Icon: Layers },
  { name: 'Layers3', Icon: Layers3 },
  { name: 'LayoutGrid', Icon: LayoutGrid },
  { name: 'Lightbulb', Icon: Lightbulb },
  { name: 'List', Icon: List },
  { name: 'ListChecks', Icon: ListChecks },
  { name: 'ListTodo', Icon: ListTodo },
  { name: 'Loader2', Icon: Loader2 },
  { name: 'LoaderCircle', Icon: LoaderCircle },
  { name: 'LogOut', Icon: LogOut },
  { name: 'Mail', Icon: Mail },
  { name: 'Megaphone', Icon: Megaphone },
  { name: 'Menu', Icon: Menu },
  { name: 'Merge', Icon: Merge },
  { name: 'MessageCircle', Icon: MessageCircle },
  { name: 'MessageCircleQuestion', Icon: MessageCircleQuestion },
  { name: 'MessageSquare', Icon: MessageSquare },
  { name: 'MessagesSquare', Icon: MessagesSquare },
  { name: 'Microchip', Icon: Microchip },
  { name: 'Minimize2', Icon: Minimize2 },
  { name: 'Minus', Icon: Minus },
  { name: 'Monitor', Icon: Monitor },
  { name: 'MoreHorizontal', Icon: MoreHorizontal },
  { name: 'MoreVertical', Icon: MoreVertical },
  { name: 'Package', Icon: Package },
  { name: 'PanelRightClose', Icon: PanelRightClose },
  { name: 'PanelRightOpen', Icon: PanelRightOpen },
  { name: 'Paperclip', Icon: Paperclip },
  { name: 'Pause', Icon: Pause },
  { name: 'PauseCircle', Icon: PauseCircle },
  { name: 'Pencil', Icon: Pencil },
  { name: 'Pin', Icon: Pin },
  { name: 'PinOff', Icon: PinOff },
  { name: 'Play', Icon: Play },
  { name: 'PlayCircle', Icon: PlayCircle },
  { name: 'Plus', Icon: Plus },
  { name: 'Power', Icon: Power },
  { name: 'PowerOff', Icon: PowerOff },
  { name: 'Puzzle', Icon: Puzzle },
  { name: 'RefreshCw', Icon: RefreshCw },
  { name: 'RotateCcw', Icon: RotateCcw },
  { name: 'Search', Icon: Search },
  { name: 'Send', Icon: Send },
  { name: 'Server', Icon: Server },
  { name: 'Settings', Icon: Settings },
  { name: 'Settings2', Icon: Settings2 },
  { name: 'Share2', Icon: Share2 },
  { name: 'Shield', Icon: Shield },
  { name: 'ShieldCheck', Icon: ShieldCheck },
  { name: 'Slack', Icon: Slack },
  { name: 'Smartphone', Icon: Smartphone },
  { name: 'Sparkles', Icon: Sparkles },
  { name: 'Square', Icon: Square },
  { name: 'SquareKanban', Icon: SquareKanban },
  { name: 'StickyNote', Icon: StickyNote },
  { name: 'StopCircle', Icon: StopCircle },
  { name: 'Terminal', Icon: Terminal },
  { name: 'TestTube', Icon: TestTube },
  { name: 'ThumbsDown', Icon: ThumbsDown },
  { name: 'ThumbsUp', Icon: ThumbsUp },
  { name: 'Trash', Icon: Trash },
  { name: 'Trash2', Icon: Trash2 },
  { name: 'TriangleAlert', Icon: TriangleAlert },
  { name: 'User', Icon: User },
  { name: 'UserCircle2', Icon: UserCircle2 },
  { name: 'Users', Icon: Users },
  { name: 'Webhook', Icon: Webhook },
  { name: 'Wrench', Icon: Wrench },
  { name: 'X', Icon: X },
  { name: 'XCircle', Icon: XCircle },
  { name: 'Zap', Icon: Zap },
];

export function PrototypeLucideIconGrid() {
  return (
    <div className="w-full max-w-full">
      <p className="mb-3 text-xs text-muted-foreground">
        {prototypeLucideIconEntries.length} icons — import from{' '}
        <code className="rounded bg-muted px-1 font-mono text-[11px]">lucide-react</code>
      </p>
      <div className="grid max-h-[min(70vh,520px)] grid-cols-2 gap-2 overflow-y-auto rounded-lg border border-border bg-muted/20 p-3 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 xl:grid-cols-8">
        {prototypeLucideIconEntries.map(({ name, Icon }) => (
          <div
            key={name}
            className="flex flex-col items-center gap-1.5 rounded-md border border-border/60 bg-card px-1 py-2 text-center"
            title={name}
          >
            <Icon className="h-5 w-5 shrink-0 text-foreground" aria-hidden />
            <span className="line-clamp-2 w-full break-words text-[10px] leading-tight text-muted-foreground">
              {name}
            </span>
          </div>
        ))}
      </div>
    </div>
  );
}
